# GitLab CI/CD Example - Agentful with Claude Code
#
# This example shows how to use agentful agents with Claude Code in GitLab CI/CD.
# Claude Code integrates natively with GitLab via @claude mentions in issues and MRs.
#
# How it works:
# 1. agentful generates specialized agents in .claude/agents/
# 2. Claude Code reads agent definitions from your repository
# 3. Comment @claude in issues/MRs to trigger AI-powered development
# 4. Claude creates merge requests with implemented changes
#
# Use Cases:
# - "@claude implement this feature using the backend agent"
# - "@claude review this MR with the reviewer agent"
# - "@claude fix test failures with the fixer agent"
# - "@claude add frontend components for this feature"
#
# Setup Instructions:
# 1. Copy this file to .gitlab-ci.yml in your repository root
# 2. Add ANTHROPIC_API_KEY to GitLab CI/CD variables:
#    - Navigate to: Settings > CI/CD > Variables
#    - Add variable: ANTHROPIC_API_KEY
#    - Mark as: Protected, Masked
#    - Value: Your Anthropic API key
# 3. Configure agentful in your project:
#    - Run: npx @itz4blitz/agentful init
#    - This creates .claude/agents/ with specialized agents
# 4. Create CLAUDE.md in repository root (optional but recommended):
#    - Define coding standards
#    - Specify review criteria
#    - Set project-specific guidelines
# 5. Start using @claude mentions in issues and merge requests

# Define pipeline stages
stages:
  - setup
  - ai
  - validate

# Global variables
variables:
  NODE_VERSION: "24"
  AGENTFUL_VERSION: "latest"

# Install agentful and generate agents (runs once per pipeline)
setup:agentful:
  stage: setup
  image: node:${NODE_VERSION}-alpine
  rules:
    # Run on merge requests
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    # Run on pushes to main
    - if: '$CI_COMMIT_BRANCH == "main"'
    # Allow manual triggers
    - if: '$CI_PIPELINE_SOURCE == "web"'
  script:
    - echo "Installing agentful..."
    - npm install -g @itz4blitz/agentful@${AGENTFUL_VERSION}

    - echo "Checking agentful setup..."
    - |
      if [ ! -d ".claude/agents" ]; then
        echo "⚠️  No agents found. Run 'npx agentful init' locally first."
        exit 1
      fi

    - echo "✅ Agentful setup verified"
    - echo "Available agents:"
    - ls -1 .claude/agents/ | sed 's/\.md$//' | sed 's/^/  - /'
  artifacts:
    paths:
      - .claude/
    expire_in: 1 hour

# Claude Code integration - responds to @claude mentions
claude:code:
  stage: ai
  image: node:${NODE_VERSION}-alpine
  needs:
    - setup:agentful
  rules:
    # Trigger on @claude mentions in MR discussions
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    # Allow manual execution with agent selection
    - if: '$CI_PIPELINE_SOURCE == "web"'
  before_script:
    # Install Claude Code CLI
    - curl -fsSL https://claude.ai/install.sh | sh
  script:
    # Claude Code reads from .claude/agents/ automatically
    # Use agentful's specialized agents via natural language
    - |
      if [ -n "$CLAUDE_AGENT" ]; then
        # Manual trigger with specific agent
        claude -p "Use the ${CLAUDE_AGENT} agent to: ${CLAUDE_TASK}"
      else
        # Default: review MR with reviewer agent
        claude -p "Review this merge request using the reviewer agent. Check:
          - Type safety and linting
          - Test coverage (minimum 80%)
          - Security vulnerabilities
          - Code quality and best practices
          - Dead code detection

          Generate a summary of findings and suggest fixes."
      fi
  artifacts:
    reports:
      # Claude Code may generate test results
      junit: .agentful/test-results.xml
    paths:
      - .agentful/
    expire_in: 1 week
    when: always

# Backend agent - triggered by backend file changes
backend:agent:
  stage: ai
  image: node:${NODE_VERSION}-alpine
  needs:
    - setup:agentful
  rules:
    # Only run if backend files changed
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - src/api/**/*
        - src/services/**/*
        - src/repositories/**/*
        - lib/backend/**/*
  before_script:
    - curl -fsSL https://claude.ai/install.sh | sh
  script:
    - |
      claude -p "Use the backend agent to review and improve these changes. Focus on:
        - API endpoint implementation
        - Service layer logic
        - Repository patterns
        - Database queries optimization
        - Error handling and validation
        - Security concerns (SQL injection, auth)"
  artifacts:
    paths:
      - .agentful/
    expire_in: 1 week

# Frontend agent - triggered by frontend file changes
frontend:agent:
  stage: ai
  image: node:${NODE_VERSION}-alpine
  needs:
    - setup:agentful
  rules:
    # Only run if frontend files changed
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - src/components/**/*
        - src/pages/**/*
        - src/styles/**/*
        - lib/frontend/**/*
  before_script:
    - curl -fsSL https://claude.ai/install.sh | sh
  script:
    - |
      claude -p "Use the frontend agent to review and improve these changes. Focus on:
        - Component implementation
        - State management
        - API integration
        - Accessibility (a11y)
        - Performance optimization
        - Responsive design"
  artifacts:
    paths:
      - .agentful/
    expire_in: 1 week

# Quality validation - runs after AI agents
validate:quality:
  stage: validate
  image: node:${NODE_VERSION}-alpine
  needs:
    - claude:code
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  script:
    - npm ci

    # Run quality gates
    - echo "Running quality gates..."

    # Type checking
    - |
      if [ -f "tsconfig.json" ]; then
        echo "Checking TypeScript types..."
        npx tsc --noEmit || echo "⚠️  Type errors found"
      fi

    # Linting
    - |
      if [ -f ".eslintrc.json" ] || [ -f ".eslintrc.js" ]; then
        echo "Running ESLint..."
        npm run lint || echo "⚠️  Linting errors found"
      fi

    # Tests
    - echo "Running tests..."
    - npm test || echo "⚠️  Test failures found"

    # Coverage
    - |
      if [ -f "coverage/coverage-summary.json" ]; then
        COVERAGE=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
        echo "Code coverage: ${COVERAGE}%"
        if (( $(echo "$COVERAGE < 80" | bc -l) )); then
          echo "⚠️  Coverage below 80%"
        fi
      fi

    # Check validation results
    - |
      if [ -f ".agentful/last-validation.json" ]; then
        echo "✅ Validation results saved"
        cat .agentful/last-validation.json
      fi
  artifacts:
    reports:
      junit: .agentful/test-results.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    paths:
      - .agentful/last-validation.json
      - coverage/
    expire_in: 1 week
    when: always

# Configuration Notes:
#
# @claude Mention Examples:
#
# In GitLab issues:
#   "@claude implement user authentication using the backend agent"
#   "@claude add login form UI with the frontend agent"
#   "@claude write tests for the auth service with the tester agent"
#
# In merge request discussions:
#   "@claude review this code with the reviewer agent"
#   "@claude fix the linting errors with the fixer agent"
#   "@claude optimize this database query"
#
# In review threads (specific lines):
#   "@claude suggest a better approach for this error handling"
#   "@claude add input validation here"
#
# Manual Pipeline Variables (for web triggers):
#   CLAUDE_AGENT: backend | frontend | reviewer | tester | fixer
#   CLAUDE_TASK: "Description of what to do"
#
# Example manual trigger:
#   Variables:
#     CLAUDE_AGENT: backend
#     CLAUDE_TASK: Implement caching for the user profile API
#
# agentful Integration:
#
# agentful provides specialized agents that Claude Code can use:
#   - backend: APIs, services, repositories, database
#   - frontend: Components, pages, state management
#   - tester: Unit tests, integration tests, E2E tests
#   - reviewer: Code quality, security, dead code detection
#   - fixer: Auto-fix validation failures
#   - orchestrator: Coordinate complex multi-agent workflows
#
# These agents are defined in .claude/agents/ and customized to your tech stack.
#
# CLAUDE.md Configuration (optional):
#
# Create a CLAUDE.md file in your repository root to guide Claude's behavior:
#
# ```markdown
# # Project Guidelines for Claude Code
#
# ## Code Style
# - Use TypeScript strict mode
# - Follow Airbnb style guide
# - Maximum line length: 100 characters
#
# ## Review Criteria
# - All functions must have JSDoc comments
# - Minimum 80% test coverage required
# - No console.log in production code
#
# ## Agent Preferences
# - backend: Use repository pattern, avoid direct DB access
# - frontend: Use React hooks, avoid class components
# - tester: Use Vitest, prefer integration over unit tests
# ```
#
# Cloud Provider Setup (alternatives to Anthropic API):
#
# AWS Bedrock:
#   Variables:
#     AWS_ACCESS_KEY_ID: your-access-key
#     AWS_SECRET_ACCESS_KEY: your-secret-key
#     AWS_REGION: us-east-1
#
# Google Vertex AI:
#   Variables:
#     GOOGLE_APPLICATION_CREDENTIALS: path/to/service-account.json
#     GOOGLE_CLOUD_PROJECT: your-project-id
#
# Security Best Practices:
# - Always mark API keys as "Masked" and "Protected"
# - Use separate API keys for production/staging
# - Rotate keys regularly
# - Limit API key permissions to minimum required
# - Monitor API usage in Anthropic Console
